#!/usr/bin/env python3
# =============================================================================
# Tools/glsl_parity/glsl_to_cpp.py — the shared GLSL -> C++ transpiler.
#
# The shaders' planetary math is written in a deliberately small subset of
# GLSL (floats, vec2/3/4, ivec3, uint, structs, for-loops, out-parameters) so
# it can be mechanically re-hosted on the CPU. Two tools use it:
#
#   check_parity.py    proves Noise.glsl / Terrain.glsl are bit-exact ports of
#                      the engine headers (the collision invariant);
#   ../planet_preview  renders the shading module to an image without a GPU,
#                      so the LOOK of a change can be reviewed in CI.
#
# Nothing here runs at game time; it exists so that "the shader and the
# collider agree" is a check rather than a hope.
# =============================================================================
import os
import re

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# GLSL "1.0" is a float; C++ "1.0" is a double. Without the suffix whole
# expressions would silently promote and diverge from the shader in the last
# bits — exactly the class of bug this tooling exists to catch.
FLOAT_LITERAL = re.compile(r"(?<![\w.])(\d+\.\d*(?:[eE][+-]?\d+)?)(?![fFuU\w.])")

# GLSL out-parameters become C++ references.
OUT_PARAM = re.compile(r"\bout\s+(float|int|uint|vec2|vec3|vec4|ivec3)\s+")

SHIM = r"""// --- GLSL -> C++ shim (generated by Tools/glsl_parity/glsl_to_cpp.py) ------
#include <cstdint>
#include <glm/glm.hpp>
using vec2 = glm::vec2;
using vec3 = glm::vec3;
using vec4 = glm::vec4;
using ivec3 = glm::ivec3;
using uint = std::uint32_t;
using glm::abs;
using glm::acos;
using glm::ceil;
using glm::degrees;
using glm::exp;
using glm::cos;
using glm::sin;
using glm::pow;
using glm::clamp;
using glm::cross;
using glm::dot;
using glm::exp2;
using glm::floor;
using glm::fract;
using glm::length;
using glm::log2;
using glm::max;
using glm::min;
using glm::mix;
using glm::normalize;
using glm::sqrt;
namespace glsl {
"""


def transpile_file(path: str) -> str:
    lines = []
    for line in open(path, encoding="utf-8").read().splitlines():
        if line.strip().startswith("#"):  # guards and includes: handled here
            continue
        line = FLOAT_LITERAL.sub(r"\1f", line)
        line = OUT_PARAM.sub(lambda m: m.group(1) + "& ", line)
        lines.append(line)
    return "\n".join(lines)


def transpile(shader_names) -> str:
    """Returns a C++ translation unit fragment: shim + namespace glsl { ... }.

    The caller closes the namespace and adds its own harness.
    """
    shaders = os.path.join(REPO, "Shaders")
    body = "\n".join(transpile_file(os.path.join(shaders, name)) for name in shader_names)
    return SHIM + body
